<a href="https://colab.research.google.com/github/AjayNRG/Machine_Learning_Algorithms_Giuseppe_Bonnacorso/blob/master/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Naive Bayes in scikit-learn

####1. Bernoulli naive Bayes

In [0]:
from sklearn.datasets import make_classification
nb_samples = 300
X, Y = make_classification(n_samples=nb_samples, n_features=2,n_informative=2,n_redundant=0)

In [0]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.25)

In [4]:
bnb = BernoulliNB(binarize=0.0)
bnb.fit(X_train,Y_train)
bnb.score(X_test,Y_test)

0.96

In [6]:
import numpy as np
data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
bnb.predict(data)

array([0, 1, 0, 1])

####2. Multinomial naive Bayes

In [0]:
from sklearn.feature_extraction import DictVectorizer

data = [
        {'house': 100, 'street': 50, 'shop': 25, 'car': 100, 'tree': 20},
        {'house': 5, 'street': 5, 'shop': 0, 'car': 10, 'tree': 500, 'river': 1}
]

In [8]:
dv = DictVectorizer(sparse=False)
X = dv.fit_transform(data)
Y = np.array([1,0])
X

array([[100., 100.,   0.,  25.,  50.,  20.],
       [ 10.,   5.,   1.,   0.,   5., 500.]])

In [9]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(X,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
test_data = data = [
                    {'house': 80, 'street': 20, 'shop': 15, 'car': 70, 'tree': 10, 'river':1},
                    {'house': 10, 'street': 5, 'shop': 1, 'car': 8, 'tree': 300, 'river': 0}
]

In [11]:
mnb.predict(dv.fit_transform(test_data))

array([1, 0])

####3. Gaussian naive Bayes

In [0]:
from sklearn.datasets import make_classification

nb_samples = 300
X, Y = make_classification(n_samples=nb_samples, n_features=2,n_informative=2, n_redundant=0)

In [14]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.25)

gnb = GaussianNB()
gnb.fit(X_train, Y_train)
Y_gnb_score = gnb.predict_proba(X_test)
Y_gnb_score[:5]

array([[9.48318692e-01, 5.16813076e-02],
       [4.35880437e-14, 1.00000000e+00],
       [7.29561493e-30, 1.00000000e+00],
       [4.46103538e-15, 1.00000000e+00],
       [2.27374008e-25, 1.00000000e+00]])

In [18]:
lr = LogisticRegression()
lr.fit(X_train, Y_train)
Y_lr_score = lr.decision_function(X_test)
Y_lr_score[:5]

array([-1.70247472,  5.76956566,  9.57536037,  5.61372063,  8.18717792])

In [0]:
fpr_gnb, tpr_gnb, thresholds_gnb = roc_curve(Y_test, Y_gnb_score[:, 1])

In [0]:
fpr_lr, tpr_lr, thresholds_lr = roc_curve(Y_test, Y_lr_score)

In [0]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score

In [0]:
digits = load_digits()

In [0]:
gnb = GaussianNB()
mnb = MultinomialNB()

In [24]:
cross_val_score(gnb, digits.data, digits.target, scoring='accuracy',cv=10).mean()

0.8113904407200497

In [25]:
cross_val_score(mnb, digits.data, digits.target, scoring='accuracy',cv=10).mean()

0.8797858472998138